name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user

            # Stop and remove old container
            docker stop myapp || true
            docker rm myapp || true

            # Remove old image
            docker rmi devops-node-app || true

            # Rebuild image
            docker build -t devops-node-app .

            # Run container
            docker run -d -p 3000:3000 --name myapp devops-node-app